"""add clicks field

Revision ID: 1034a3e36dec
Revises: a65117de6949
Create Date: 2026-03-23 16:59:09.532103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1034a3e36dec'
down_revision: Union[str, Sequence[str], None] = 'a65117de6949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('clicks', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'clicks')
    # ### end Alembic commands ###
